version: "3"
services:
  dawnstar-backend:
    container_name: dawnstar-backend
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - dawnstar-db
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todo-db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  dawnstar-db:
    container_name: dawnstar-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dawnstardb
    networks:
      - dawnstar-db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.1
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: kennguch3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgress
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - dawnstar-db
    networks:
      - dawnstar-db

networks:
  dawnstar-db:
    driver: bridge
volumes:
  dawnstar-db:
  pgadmin-data:
