version: "3"
services:
  dawnstar-backend:
    image: dawnstar-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dawnstar-db
      - dawnstar-redis
    restart: on-failure
    environment:
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      DB_HOST: dawnstar-db
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    expose:
      - ${APP_PORT}
    networks:
      - ./utils/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - dawnstar

  dawnstar-pgadmin:
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    volumes:
      - ./utils/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./utils/pgpass:/pgpass # passwords for the connections in this files
    depends_on:
      - dawnstar-db
    networks:
      - dawnstar

  dawnstar-redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dawnstar

  dawnstar-rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dawnstar
    restart: on-failure

networks:
  dawnstar:
    driver: bridge