version: "3"
services:
  dawnstar-backend:
    container_name: dawnstar-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dawnstar-db
      - dawnstar-redis
    restart: on-failure
    environment:
      APP_PORT: 3000
      APP_ENV: "development"
      APP_NAME: "development"
      DB_HOST: "dawnstar-db"
      DB_NAME: "dawnstardb"
      DB_PORT: 5432
    ports:
      - "3000:3000"
    networks:
      - dawnstar-db

  dawnstar-db:
    container_name: dawnstar-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./utils/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dawnstardb
    networks:
      - dawnstar-db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: kennguch3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./utils/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./utils/pgpass:/pgpass # passwords for the connections in this files
    depends_on:
      - dawnstar-db
    networks:
      - dawnstar-db

  dawnstar-redis:
    container_name: dawnstar-redis
    image: redis:6.2.6-alpine
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"
    networks:
      - dawnstar-db
networks:
  dawnstar-db:
    driver: bridge
volumes:
  dawnstar-db:
  pgadmin-data:
