version: "3.8"
services:
  dawnstar-backend:
    image: dawnstar-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      dawnstar-db:
        condition: service_healthy
      dawnstar-redis:
        condition: service_healthy
      dawnstar-rabbitmq:
        condition: service_healthy
    environment:
      APP_PORT: ${APP_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
      DB_HOST: dawnstar-db
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      WAIT_HOSTS: dawnstar-db:5432,dawnstar-redis:6379,dawnstar-rabbitmq:5672
    restart: on-failure
    expose:
      - "${APP_PORT}"
    networks:
      - dawnstar
  dawnstar-db:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./utils/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dawnstar

  dawnstar-pgadmin:
    image: dpage/pgadmin4:6.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    volumes:
      - ./utils/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./utils/pgpass:/pgpass # passwords for the connections in this files
    depends_on:
      - dawnstar-db
    networks:
      - dawnstar

  dawnstar-redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dawnstar
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
  dawnstar-nginx:
    image: dawnstar-nginx
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://localhost || exit 1" ]
      timeout: 10s
    depends_on:
      - dawnstar-backend
    networks:
      - dawnstar

  dawnstar-rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dawnstar
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics",'-q', "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure

networks:
  dawnstar:
    driver: bridge