name: Dawnstar Docker Compose Workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container Stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:dawnstar-backend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
