name: Dawnstar Node JS Workflow

<<<<<<< Updated upstream
on: [ push, pull_request ]
=======
on: [push, pull_request]
>>>>>>> Stashed changes

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< Updated upstream
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
=======
        node-version: [10.x, 12.x, 14.x, 15.x]
>>>>>>> Stashed changes

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
#      - run: npm test