name: Dawnstar Docker Compose Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Container Stack

        id: build-container-stack

        env:
          DB_USER: ${{secrets.DB_USER}}

        run: docker-compose up -d
